### ISSUE TITLE
make shell error

### ISSUE THREAD

**Issue by schmurtzm** [s0ckz/trimui-smart-pro-toolchain#1]
Hi, I'm not able to build it correctly : 

```
Step 9/14 : RUN ./setup-toolchain.sh
 ---> Running in 7ae666f45cc4
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c ./setup-toolchain.sh' returned a non-zero code: 2
```

**Comment by schmurtzm** [comment]
Fixed after adding the required files manually.

**Comment by jgassie** [comment]
> Fixed after adding the required files manually.

Where did you put the files?  I put them in root, but it must be expecting them in a container which I'm not sure how to access.  Not a linux guy of course.
[update] - OK, I guess they had to be under 'support', but somehow the files weren't copied there properly the first time.
